"""add players and per game table

Revision ID: 9cbe743aff49
Revises: 
Create Date: 2020-10-27 16:25:45.786145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cbe743aff49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('per_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('season', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('league', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('games', sa.String(length=255), nullable=True),
    sa.Column('games_started', sa.String(length=255), nullable=True),
    sa.Column('minutes_played', sa.Integer(), nullable=True),
    sa.Column('field_goals', sa.String(length=255), nullable=True),
    sa.Column('field_goal_attempts', sa.Float(), nullable=True),
    sa.Column('field_goal_percentage', sa.Float(), nullable=True),
    sa.Column('three_pointers', sa.Float(), nullable=True),
    sa.Column('three_point_attempts', sa.Float(), nullable=True),
    sa.Column('three_point_percentage', sa.Float(), nullable=True),
    sa.Column('two_pointers', sa.Float(), nullable=True),
    sa.Column('two_point_attempts', sa.Float(), nullable=True),
    sa.Column('two_point_percentage', sa.Float(), nullable=True),
    sa.Column('effective_field_goal_percentage', sa.Float(), nullable=True),
    sa.Column('free_throws', sa.Float(), nullable=True),
    sa.Column('free_throw_attempts', sa.Float(), nullable=True),
    sa.Column('free_throw_percentage', sa.Float(), nullable=True),
    sa.Column('offensive_rebound_total', sa.Float(), nullable=True),
    sa.Column('defensive_rebound_total', sa.Float(), nullable=True),
    sa.Column('rebound_total', sa.Float(), nullable=True),
    sa.Column('assists', sa.Float(), nullable=True),
    sa.Column('steals', sa.Float(), nullable=True),
    sa.Column('blocks', sa.Float(), nullable=True),
    sa.Column('turnovers', sa.Float(), nullable=True),
    sa.Column('personal_fouls', sa.Float(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='unique_player_season')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('per_game')
    # ### end Alembic commands ###
