"""add advanced table

Revision ID: fd3a75bfa3e5
Revises: 9cbe743aff49
Create Date: 2020-11-01 18:28:59.045977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3a75bfa3e5'
down_revision = '9cbe743aff49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advanced',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('season', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('league', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('games', sa.String(length=255), nullable=True),
    sa.Column('minutes_played', sa.Integer(), nullable=True),
    sa.Column('per', sa.Float(), nullable=True),
    sa.Column('ts', sa.Float(), nullable=True),
    sa.Column('three_point_attempt_rate', sa.Float(), nullable=True),
    sa.Column('free_throw_attempt_rate', sa.Float(), nullable=True),
    sa.Column('orb', sa.Float(), nullable=True),
    sa.Column('drb', sa.Float(), nullable=True),
    sa.Column('trb', sa.Float(), nullable=True),
    sa.Column('ast', sa.Float(), nullable=True),
    sa.Column('stl', sa.Float(), nullable=True),
    sa.Column('blk', sa.Float(), nullable=True),
    sa.Column('tov', sa.Float(), nullable=True),
    sa.Column('usg', sa.Float(), nullable=True),
    sa.Column('ows', sa.Float(), nullable=True),
    sa.Column('dws', sa.Float(), nullable=True),
    sa.Column('ws', sa.Float(), nullable=True),
    sa.Column('ws_48', sa.Float(), nullable=True),
    sa.Column('obpm', sa.Float(), nullable=True),
    sa.Column('dbpm', sa.Float(), nullable=True),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('vorp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='unique_player_season')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advanced')
    # ### end Alembic commands ###
